name: my_flutter_starter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.2
  intl: ^0.18.0
  logger: ^1.1.0
  retrofit: ^3.3.1
  sentry_flutter: ^6.12.2

dev_dependencies:
  build_runner: ^2.3.0
  dart_code_metrics: ^4.21.0
  flutter_flavorizr: ^2.1.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.1
  # mockito: ^5.3.2
  pretty_dio_logger: ^1.1.1
  retrofit_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    dev:
      app:
        name: "${APP_NAME} Dev"
      android:
        applicationId: "${ID_DEV}"

      ios:
        bundleId: "${ID_DEV}"

    staging:
      app:
        name: "${APP_NAME} Staging"
      android:
        applicationId: "${ID_STAGING}"

      ios:
        bundleId: "${ID_STAGING}"

    prod:
      app:
        name: "${APP_NAME}"
      android:
        applicationId: "${ID_PROD}"

      ios:
        bundleId: "${ID_PROD}"
